### ISSUE TITLE
Terms of Service Link don't present on top of current Affirm View Controller

### ISSUE THREAD

**Issue by Mistobaan** [Affirm/affirm-ios-sdk#1]
We are showing the Affirm View on a Modal dialog. If the user click the Affirms Terms of Service Link, the page will open on the root tab controller inside of being displayed on top of the current view.

**Comment by curtiscook** [comment]
This should be fixed as of 3.0.0

**Comment by affirmPE** [comment]
------------------------------------------------------------------------------------------------------------
Type your response on top of this email to respond to this case. Learn Email Commands Here - https://support.desk.com/customer/portal/articles/1191712-reply-via-email-commands
------------------------------------------------------------------------------------------------------------


Case Assignment Notification - Case #16128 ( https://affirm.desk.com/web/agent/case/16128 )

Affirm | Jun 21, 2017 08:35PM UTC

------------------------------------------------------------------------------------------------------------
Case #16128
Customer: Affirm/affirm-ios-sdk
Subject: Re: [Affirm/affirm-ios-sdk] Terms of Service Link don&#x27;t present on top of current Affirm View Controller (#1)
------------------------------------------------------------------------------------------------------------
Case Information (16128):

Subject: Re: [Affirm/affirm-ios-sdk] Terms of Service Link don&#x27;t present on top of current Affirm View Controller (#1)

Description: 
Status: Open
Priority: 4

Assigned Group: MTS



------------------------------------------------------------------------------------------------------------
Case History
------------------------------------------------------------------------------------------------------------
 goatmad  at JUN 21, 2017 | 01:35PM PDT:
Closed #1.

-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/Affirm/affirm-ios-sdk/issues/1#event-1133637560

------------------------------------------------------------------------------------------------------------
This message was sent to reply@reply.github.com in reference to Case #16128
------------------------------------------------------------------------------------------------------------

**Comment by affirmPE** [comment]
------------------------------------------------------------------------------------------------------------
Type your response on top of this email to respond to this case. Learn Email Commands Here - https://support.desk.com/customer/portal/articles/1191712-reply-via-email-commands
------------------------------------------------------------------------------------------------------------


Case Assignment Notification - Case #16127 ( https://affirm.desk.com/web/agent/case/16127 )

Affirm | Jun 21, 2017 08:35PM UTC

------------------------------------------------------------------------------------------------------------
Case #16127
Customer: Affirm/affirm-ios-sdk
Subject: Re: [Affirm/affirm-ios-sdk] Terms of Service Link don&#x27;t present on top of current Affirm View Controller (#1)
------------------------------------------------------------------------------------------------------------
Case Information (16127):

Subject: Re: [Affirm/affirm-ios-sdk] Terms of Service Link don&#x27;t present on top of current Affirm View Controller (#1)

Description: 
Status: Open
Priority: 4

Assigned Group: MTS



------------------------------------------------------------------------------------------------------------
Case History
------------------------------------------------------------------------------------------------------------
 goatmad  at JUN 21, 2017 | 01:35PM PDT:
This should be fixed as of 3.0.0

-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/Affirm/affirm-ios-sdk/issues/1#issuecomment-310197119

------------------------------------------------------------------------------------------------------------
This message was sent to reply@reply.github.com in reference to Case #16127
------------------------------------------------------------------------------------------------------------
