### ISSUE TITLE
WKWebView appearance issue while presenting modal

### ISSUE THREAD

**Issue by jayesh15111988** [Affirm/affirm-ios-sdk#12]
We are using Affirm SDK in our Wayfair iOS app. In recent version we're seeing unintended behavior while trying to present `AffirmBaseModalViewController` from the app. The issue occurs where base web view (WKWebView) is positioned awkwardly in the scene. (Attaching screenshots for reference)

We started experiencing this problem when Affirm SDK upgraded its web view from basic `UIWebView` to `WKWebView`. As per our observation, Affirm payment modal was presented properly before SDK received this update. 

We tried to debug this bug on our end as much as possible with no luck. This bug appears on both simulator and actual iOS device. It is bit more confusing, since `AffirmBaseModalViewController` shows the correct behavior on the demo app that is provided along with library. Have any of your other users experienced similar problem? Let us know if you need any other information from our end that can make debugging easier for you.

**App preview**
<br/>

![simulator screen shot - iphone 6 - 2018-01-11 at 17 21 00](https://user-images.githubusercontent.com/6687735/34850736-27388ca2-f6f5-11e7-91f7-ccb028a5ed7a.png)

**View Debugger output**
<br/>

<img width="720" alt="screen shot 2018-01-11 at 5 21 04 pm" src="https://user-images.githubusercontent.com/6687735/34850694-f6fe4df6-f6f4-11e7-9aa7-2a8ff6cf71d4.png">

<br/>

**Comment by affirmPE** [comment]
------------------------------------------------------------------------------------------------------------
Type your response on top of this email to respond to this case. Learn Email Commands Here - https://support.desk.com/customer/portal/articles/1191712-reply-via-email-commands
------------------------------------------------------------------------------------------------------------


Case Assignment Notification - Case #204405 ( https://affirm.desk.com/web/agent/case/204405 )

Affirm | Jan 11, 2018 10:32PM UTC

------------------------------------------------------------------------------------------------------------
Case #204405
Customer: Affirm/affirm-ios-sdk
Subject: [Affirm/affirm-ios-sdk] WKWebView appearance issue while presenting modal (#12)
------------------------------------------------------------------------------------------------------------
Case Information (204405):

Subject: [Affirm/affirm-ios-sdk] WKWebView appearance issue while presenting modal (#12)

Description: 
Status: Open
Priority: 4

Assigned Group: MTS



------------------------------------------------------------------------------------------------------------
Case History
------------------------------------------------------------------------------------------------------------
 goatmad  at JAN 11, 2018 | 02:32PM PST:
We are using Affirm SDK in our Wayfair iOS app. In recent version we're seeing unintended behavior while trying to present `AffirmBaseModalViewController` from the app. The issue occurs where base web view (WKWebView) is positioned awkwardly in the scene. (Attaching screenshots for reference)

We started experiencing this problem when Affirm SDK upgraded its web view from basic `UIWebView` to `WKWebView`. As per our observation, Affirm payment modal was presented properly before SDK received this update. 

We tried to debug this bug on our end as much as possible with no luck. This bug appears on both simulator and actual iOS device. It is bit more confusing, since `AffirmBaseModalViewController` shows the correct behavior on the demo app that is provided along with library. Have any of your other users experienced similar problem? Let us know if you need any other information from our end that can make debugging easier for you.

**App preview**
<br/>

![simulator screen shot - iphone 6 - 2018-01-11 at 17 21 00](https://user-images.githubusercontent.com/6687735/34850736-27388ca2-f6f5-11e7-91f7-ccb028a5ed7a.png)

**View Debugger output**
<br/>

<img width="720" alt="screen shot 2018-01-11 at 5 21 04 pm" src="https://user-images.githubusercontent.com/6687735/34850694-f6fe4df6-f6f4-11e7-9aa7-2a8ff6cf71d4.png">

<br/>



-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/Affirm/affirm-ios-sdk/issues/12

------------------------------------------------------------------------------------------------------------
This message was sent to reply@reply.github.com in reference to Case #204405
------------------------------------------------------------------------------------------------------------

**Comment by curtiscook** [comment]
Hi Jayesh, 

We looked into this back in September / October with Bill and were able to determine that the issue exists with the Wayfair app when even using a vanilla WKWebView. I think it would be best to debug a vanilla WKWebView first before adding extra complexity? We're happy to jump on another call, please reach out through your CSM and we can schedule something. 

Thanks!

**Comment by jayesh15111988** [comment]
@curtiscook That sounds good. Thanks for the extra pointer, we will continue investigating why it fails with vanilla WKWebView for now
