### ISSUE TITLE
Unexpected CFBundleExecutable key

### ISSUE THREAD

**Issue by rzulkoski** [Affirm/affirm-ios-sdk#13]
This issue has already been fixed in commit ecba6cc94d0307f38407b5eed6d8c0fa53820e39, however a new release that includes this change has not been created yet.

Would you be able to create a new release including this change?

**Comment by affirmPE** [comment]
------------------------------------------------------------------------------------------------------------
Type your response on top of this email to respond to this case. Learn Email Commands Here - https://support.desk.com/customer/portal/articles/1191712-reply-via-email-commands
------------------------------------------------------------------------------------------------------------


Case Assignment Notification - Case #205604 ( https://affirm.desk.com/web/agent/case/205604 )

Affirm | Feb 14, 2018 04:10PM UTC

------------------------------------------------------------------------------------------------------------
Case #205604
Customer: Affirm/affirm-ios-sdk
Subject: [Affirm/affirm-ios-sdk] Unexpected CFBundleExecutable key (#13)
------------------------------------------------------------------------------------------------------------
Case Information (205604):

Subject: [Affirm/affirm-ios-sdk] Unexpected CFBundleExecutable key (#13)

Description: 
Status: Open
Priority: 4

Assigned Group: MTS



------------------------------------------------------------------------------------------------------------
Case History
------------------------------------------------------------------------------------------------------------
 goatmad  at FEB 14, 2018 | 08:10AM PST:
This issue has already been fixed in commit ecba6cc94d0307f38407b5eed6d8c0fa53820e39, however a new release that includes this change has not been created yet.

Would you be able to create a new release including this change?

-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/Affirm/affirm-ios-sdk/issues/13

------------------------------------------------------------------------------------------------------------
This message was sent to reply@reply.github.com in reference to Case #205604
------------------------------------------------------------------------------------------------------------

**Comment by rzulkoski** [comment]
It would appear that Carthage will not build master in its current state.

**Comment by curtiscook** [comment]
You should be set in 4.0.8 
Please let us know if you are still experiencing issues

**Comment by affirmPE** [comment]
------------------------------------------------------------------------------------------------------------
Type your response on top of this email to respond to this case. Learn Email Commands Here - https://support.desk.com/customer/portal/articles/1191712-reply-via-email-commands
------------------------------------------------------------------------------------------------------------


Case Assignment Notification - Case #206034 ( https://affirm.desk.com/web/agent/case/206034 )

Affirm | Feb 27, 2018 05:11PM UTC

------------------------------------------------------------------------------------------------------------
Case #206034
Customer: Affirm/affirm-ios-sdk
Subject: Re: [Affirm/affirm-ios-sdk] Unexpected CFBundleExecutable key (#13)
------------------------------------------------------------------------------------------------------------
Case Information (206034):

Subject: Re: [Affirm/affirm-ios-sdk] Unexpected CFBundleExecutable key (#13)

Description: 
Status: Open
Priority: 4

Assigned Group: MTS



------------------------------------------------------------------------------------------------------------
Case History
------------------------------------------------------------------------------------------------------------
 goatmad  at FEB 27, 2018 | 09:11AM PST:
Closed #13.

------------------------------------------------------------------------------------------------------------
This message was sent to reply@reply.github.com in reference to Case #206034
------------------------------------------------------------------------------------------------------------

**Comment by affirmPE** [comment]
------------------------------------------------------------------------------------------------------------
Type your response on top of this email to respond to this case. Learn Email Commands Here - https://support.desk.com/customer/portal/articles/1191712-reply-via-email-commands
------------------------------------------------------------------------------------------------------------


Case Assignment Notification - Case #206035 ( https://affirm.desk.com/web/agent/case/206035 )

Affirm | Feb 27, 2018 05:11PM UTC

------------------------------------------------------------------------------------------------------------
Case #206035
Customer: Affirm/affirm-ios-sdk
Subject: Re: [Affirm/affirm-ios-sdk] Unexpected CFBundleExecutable key (#13)
------------------------------------------------------------------------------------------------------------
Case Information (206035):

Subject: Re: [Affirm/affirm-ios-sdk] Unexpected CFBundleExecutable key (#13)

Description: 
Status: Open
Priority: 4

Assigned Group: MTS



------------------------------------------------------------------------------------------------------------
Case History
------------------------------------------------------------------------------------------------------------
 goatmad  at FEB 27, 2018 | 09:11AM PST:
You should be set in 4.0.8
Please let us know if you are still experiencing issues

------------------------------------------------------------------------------------------------------------
This message was sent to reply@reply.github.com in reference to Case #206035
------------------------------------------------------------------------------------------------------------
