### ISSUE TITLE
Logout current user

### ISSUE THREAD

**Issue by mihai-moldovan** [Affirm/affirm-ios-sdk#3]
In our app the user is able to logout. We couldn't find a way to also logout current user from the Affirm SDK, so when the new user tries an Affirm payment, the old user credentials are still present.

**Comment by curtiscook** [comment]
Sorry for the late reply. This is not currently supported, but I'll add it to our internal tracking

**Comment by affirmPE** [comment]
------------------------------------------------------------------------------------------------------------
Type your response on top of this email to respond to this case. Learn Email Commands Here - https://support.desk.com/customer/portal/articles/1191712-reply-via-email-commands
------------------------------------------------------------------------------------------------------------


Case Assignment Notification - Case #16133 ( https://affirm.desk.com/web/agent/case/16133 )

Affirm | Jun 21, 2017 09:09PM UTC

------------------------------------------------------------------------------------------------------------
Case #16133
Customer: Affirm/affirm-ios-sdk
Subject: Re: [Affirm/affirm-ios-sdk] Logout current user (#3)
------------------------------------------------------------------------------------------------------------
Case Information (16133):

Subject: Re: [Affirm/affirm-ios-sdk] Logout current user (#3)

Description: 
Status: Open
Priority: 4

Assigned Group: MTS



------------------------------------------------------------------------------------------------------------
Case History
------------------------------------------------------------------------------------------------------------
 goatmad  at JUN 21, 2017 | 02:09PM PDT:
Sorry for the late reply. This is not currently supported, but I'll add it to our internal tracking

-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/Affirm/affirm-ios-sdk/issues/3#issuecomment-310206055

------------------------------------------------------------------------------------------------------------
This message was sent to reply@reply.github.com in reference to Case #16133
------------------------------------------------------------------------------------------------------------

**Comment by curtiscook** [comment]
https://github.com/Affirm/affirm-ios-sdk/blob/master/AffirmSDK/AffirmCheckoutViewController.h#L31-L35
https://github.com/Affirm/affirm-ios-sdk/blob/master/AffirmSDK/AffirmCheckoutViewController.m#L97-L104

**Comment by affirmPE** [comment]
------------------------------------------------------------------------------------------------------------
Type your response on top of this email to respond to this case. Learn Email Commands Here - https://support.desk.com/customer/portal/articles/1191712-reply-via-email-commands
------------------------------------------------------------------------------------------------------------


Case Assignment Notification - Case #16136 ( https://affirm.desk.com/web/agent/case/16136 )

Affirm | Jun 21, 2017 09:54PM UTC

------------------------------------------------------------------------------------------------------------
Case #16136
Customer: Affirm/affirm-ios-sdk
Subject: Re: [Affirm/affirm-ios-sdk] Logout current user (#3)
------------------------------------------------------------------------------------------------------------
Case Information (16136):

Subject: Re: [Affirm/affirm-ios-sdk] Logout current user (#3)

Description: 
Status: Open
Priority: 4

Assigned Group: MTS



------------------------------------------------------------------------------------------------------------
Case History
------------------------------------------------------------------------------------------------------------
 goatmad  at JUN 21, 2017 | 02:54PM PDT:
https://github.com/Affirm/affirm-ios-sdk/blob/master/AffirmSDK/AffirmCheckoutViewController.h#L31-L35
https://github.com/Affirm/affirm-ios-sdk/blob/master/AffirmSDK/AffirmCheckoutViewController.m#L97-L104

-- 
You are receiving this because you commented.
Reply to this email directly or view it on GitHub:
https://github.com/Affirm/affirm-ios-sdk/issues/3#issuecomment-310216040

------------------------------------------------------------------------------------------------------------
This message was sent to reply@reply.github.com in reference to Case #16136
------------------------------------------------------------------------------------------------------------

**Comment by affirmPE** [comment]
------------------------------------------------------------------------------------------------------------
Type your response on top of this email to respond to this case. Learn Email Commands Here - https://support.desk.com/customer/portal/articles/1191712-reply-via-email-commands
------------------------------------------------------------------------------------------------------------


Case Assignment Notification - Case #16135 ( https://affirm.desk.com/web/agent/case/16135 )

Affirm | Jun 21, 2017 09:54PM UTC

------------------------------------------------------------------------------------------------------------
Case #16135
Customer: Affirm/affirm-ios-sdk
Subject: Re: [Affirm/affirm-ios-sdk] Logout current user (#3)
------------------------------------------------------------------------------------------------------------
Case Information (16135):

Subject: Re: [Affirm/affirm-ios-sdk] Logout current user (#3)

Description: 
Status: Open
Priority: 4

Assigned Group: MTS



------------------------------------------------------------------------------------------------------------
Case History
------------------------------------------------------------------------------------------------------------
 goatmad  at JUN 21, 2017 | 02:54PM PDT:
Closed #3.

-- 
You are receiving this because you commented.
Reply to this email directly or view it on GitHub:
https://github.com/Affirm/affirm-ios-sdk/issues/3#event-1133751053

------------------------------------------------------------------------------------------------------------
This message was sent to reply@reply.github.com in reference to Case #16135
------------------------------------------------------------------------------------------------------------
