### ISSUE TITLE
AppStore upload error issue on latest pod AffirmSDK v 2.2.0 

### ISSUE THREAD

**Issue by dechhay** [Affirm/affirm-ios-sdk#5]
Using Xcode 7.3.1

I am getting an upload error after I updated Affirm from v 2.1.1 to 2.2.0.  I was able to rebuild on 2.1.1, so I'm pretty sure it has to do with 2.2.0

Here's the error:
`ERROR ITMS-90535: "Unexpected CFBundleExecutable Key. The bundle at 'Payload/MYAPPName.app/AffirmSDK.bundle' does not contain a bundle executable. If this bundle intentionally does not contain an executable, consider removing the CFBundleExecutable key from its Info.plist and using a CFBundlePackageType of BNDL. If this bundle is part of a third-party framework, consider contacting the developer of the framework for an update to address this issue."
ERROR ITMS-90535: "Unexpected CFBundleExecutable Key. The bundle at 'Payload/MYAPPName.app/AffirmSDK.bundle' does not contain a bundle executable. If this bundle intentionally does not contain an executable, consider removing the CFBundleExecutable key from its Info.plist and using a CFBundlePackageType of BNDL. If this bundle is part of a third-party framework, consider contacting the developer of the framework for an update to address this issue."`

Any ideas on why this is happening?

**Comment by affirmPE** [comment]
@goatmad Are you still having this issue?

**Comment by affirmPE** [comment]
------------------------------------------------------------------------------------------------------------
Type your response on top of this email to respond to this case. Learn Email Commands Here - https://support.desk.com/customer/portal/articles/1191712-reply-via-email-commands
------------------------------------------------------------------------------------------------------------


Case Assignment Notification - Case #16124 ( https://affirm.desk.com/web/agent/case/16124 )

Affirm | Jun 21, 2017 08:23PM UTC

------------------------------------------------------------------------------------------------------------
Case #16124
Customer: Affirm/affirm-ios-sdk
Subject: Re: [Affirm/affirm-ios-sdk] AppStore upload error issue on latest pod AffirmSDK v 2.2.0 (#5)
------------------------------------------------------------------------------------------------------------
Case Information (16124):

Subject: Re: [Affirm/affirm-ios-sdk] AppStore upload error issue on latest pod AffirmSDK v 2.2.0 (#5)

Description: 
Status: Open
Priority: 4

Assigned Group: MTS



------------------------------------------------------------------------------------------------------------
Case History
------------------------------------------------------------------------------------------------------------
 goatmad  at JUN 21, 2017 | 01:23PM PDT:
Closed #5.

-- 
You are receiving this because you commented.
Reply to this email directly or view it on GitHub:
https://github.com/Affirm/affirm-ios-sdk/issues/5#event-1133620270

------------------------------------------------------------------------------------------------------------
This message was sent to reply@reply.github.com in reference to Case #16124
------------------------------------------------------------------------------------------------------------
